### ISSUE TITLE
GHA plugin does not respect config parameter (with.config)

### ISSUE THREAD

**Issue by jortkoopmans** [haveyoudebuggedit/trojansourcedetector#1]
**The problem**

When providing an alternative configuration file, using the .with.config as outlined in the documentation;
```
      # Run trojansourcedetector
      - name: Trojan Source Detector
        uses: haveyoudebuggedit/trojansourcedetector@v1
        with:
          config: path/to/config/file
```

the observed behavior is that this configuration is not used at all and the plugin will always try to load .trojansourcedetector.json from your repository.

**Expected behavior**
Have the GHA plugin using the provided path/to/config/file.

**The solution**
I believe in the action.yml one step is omitted, which would pass the config input as an argument to the docker image. I will attach a PR.
